name: GitHub 3D Contribution Calendar

on:
  schedule:
    - cron: '0 18 * * *' # 03:00 JST == 18:00 UTC
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3

      - name: Create settings directory
        run: mkdir -p conf

      - name: Create settings file
        run: |
          cat > conf/github-profile-3d-contrib.json << EOL
          [
            {
              "type": "rainbow",
              "fileName": "night.svg",
              "backgroundColor": "#1a1b27",
              "foregroundColor": "#70a5fd",
              "strongColor": "#bf91f3",
              "weakColor": "#38bdae",
              "radarColor": "#70a5fd",
              "growingAnimation": true,
              "saturation": "50%",
              "contribLightness": [
                "20%",
                "30%",
                "35%",
                "40%",
                "50%"
              ],
              "duration": "10s",
              "hueRatio": -7
            }
          ]
          EOL

      - name: Generate 3D Contribution Calendar
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 250
          SETTING_JSON: conf/github-profile-3d-contrib.json

      - name: Push SVGs to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output-3d-contrib
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
