name: GitHub 3D Contribution Calendar

on:
  schedule:
    - cron: '0 */12 * * *' # twice per day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3

      - name: Create settings file
        run: |
          echo '{
            "type": "tokyo",
            "colors": {
              "h1": "#70a5fd",
              "h2": "#bf91f3",
              "h3": "#38bdae",
              "h4": "#1a1b27"
            }
          }' > settings.json

      - name: Generate 3D Contribution Calendar
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 250
          SETTING_JSON: settings.json

      - name: Verify Generated Files
        run: |
          ls -la profile-3d-contrib/

      - name: Commit & Push
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add profile-3d-contrib/
          git commit -m "🗃️ Generate 3D Contribution Calendar" || echo "No changes to commit"
          git push origin HEAD:${{ github.ref }} || git pull --rebase origin ${{ github.ref }} && git push origin HEAD:${{ github.ref }}
