name: GitHub 3D Contribution Calendar

on:
  schedule:
    - cron: '0 18 * * *' # Runs at 18:00 UTC (03:00 JST)
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3

      - name: Generate 3D Contribution Calendar
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 250
          SETTING_JSON: settings.json

      - name: Create settings file
        run: |
          echo '{
            "type": "tokyo",
            "colors": {
              "h1": "#70a5fd",
              "h2": "#bf91f3",
              "h3": "#38bdae",
              "h4": "#1a1b27"
            }
          }' > settings.json

      - name: Verify Generated Files
        run: |
          if [ ! -d "profile-3d-contrib" ]; then
            echo "Error: profile-3d-contrib directory not found!"
            exit 1
          fi
          echo "Generated files:"
          ls -la profile-3d-contrib/

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git commit -m "Generated 3D Contribution Calendar 🗃️" || echo "No changes to commit"
          git push
