name: GitHub 3D Contribution Calendar

on:
  schedule:
    - cron: '0 */12 * * *' # twice per day
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3

      - name: Generate 3D Contribution Calendar
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          MAX_REPOS: 250
          SETTING_JSON: '{"type":"tokyo","colors":{"h1":"#70a5fd","h2":"#bf91f3","h3":"#38bdae","h4":"#1a1b27"}}'

      - name: Verify Generated Files
        run: |
          ls -la profile-3d-contrib/
          echo "Generated files:"
          find profile-3d-contrib/ -type f -name "*.svg"

      - name: Commit & Push
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git add profile-3d-contrib/
          git commit -m "🗃️ Generate 3D Contribution Calendar" || echo "No changes to commit"
          git push origin HEAD:main --force
